#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_login_check:
  path: /api/login_check

swagger_ui:
  resource: '@HBSwaggerUiBundle/Resources/config/routing.yml'
  prefix: /docs
